spring.application.name=notification-service
server.port=8083

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

kafka.topics.payment-initiated=payment.initiated
kafka.topics.payment-completed=payment.completed